//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Queen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Queen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assertion failure..
        /// </summary>
        internal static string ExceptionAssertionFailure {
            get {
                return ResourceManager.GetString("ExceptionAssertionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to access an index out of array bounds..
        /// </summary>
        internal static string ExceptionIndexOutOfBound {
            get {
                return ResourceManager.GetString("ExceptionIndexOutOfBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to cast an object to an incompatible type..
        /// </summary>
        internal static string ExceptionInvalidCast {
            get {
                return ResourceManager.GetString("ExceptionInvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to perform an operation that is not allowed..
        /// </summary>
        internal static string ExceptionInvalidOperation {
            get {
                return ResourceManager.GetString("ExceptionInvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open a file..
        /// </summary>
        internal static string ExceptionIOError {
            get {
                return ResourceManager.GetString("ExceptionIOError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-defined non-error exception occured..
        /// </summary>
        internal static string ExceptionNonErrorUser {
            get {
                return ResourceManager.GetString("ExceptionNonErrorUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested feature is not implemented..
        /// </summary>
        internal static string ExceptionNotImplemented {
            get {
                return ResourceManager.GetString("ExceptionNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object reference is null..
        /// </summary>
        internal static string ExceptionNullReference {
            get {
                return ResourceManager.GetString("ExceptionNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overflow..
        /// </summary>
        internal static string ExceptionOverflow {
            get {
                return ResourceManager.GetString("ExceptionOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User requested to quit the application..
        /// </summary>
        internal static string ExceptionQuit {
            get {
                return ResourceManager.GetString("ExceptionQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack overflow..
        /// </summary>
        internal static string ExceptionStackOverflow {
            get {
                return ResourceManager.GetString("ExceptionStackOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application couldn&apos;t find at least one of required system files..
        /// </summary>
        internal static string ExceptionSystemFileNotFound {
            get {
                return ResourceManager.GetString("ExceptionSystemFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined exception occured..
        /// </summary>
        internal static string ExceptionUndefined {
            get {
                return ResourceManager.GetString("ExceptionUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-defined exception occured..
        /// </summary>
        internal static string ExceptionUser {
            get {
                return ResourceManager.GetString("ExceptionUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-defined local exception occured..
        /// </summary>
        internal static string ExceptionUserLocal {
            get {
                return ResourceManager.GetString("ExceptionUserLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to divide an integer by zero..
        /// </summary>
        internal static string ExceptionZeroDivision {
            get {
                return ResourceManager.GetString("ExceptionZeroDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal exception occured..
        /// </summary>
        internal static string InternalException {
            get {
                return ResourceManager.GetString("InternalException", resourceCulture);
            }
        }
    }
}
